#! /bin/dash
# First of all, always check if the .girt exists
girtinit=`ls .girt 2>/dev/null`
if test -z "$girtinit"
then
    echo "girt-log: error: girt repository directory .girt not found"
    exit 1
fi
tac .girt/log.txt
